baseURL: "/conference-notes/"
languageCode: "en-us"
title: "Ken's Conference Notes"
theme: "minimo"
enableEmoji: true
publishDir: "docs"

params:
  search:
    client: fuse
  info:
    description: My collection of notes from conferences I've attended
    title404: Nothing's here!
  sidebar:
    enable: true
  widgets:
    header:
      - breadcrumbs
    sidebar:
      - about
      - search
      - sidebar_menu
      - taxonomy_cloud
  settings:
    hideMainMenu: true

taxonomies:
    category: "categories"
    tag: "tags"
